[package]
name = "semver-increase"
version = "0.2.0"
edition = "2021"

[dependencies]
semver = "1.0.23"
clap = { version = "4.5.6", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
lazy_static = "1.4.0"

[lints.clippy]
pedantic = "deny"
