[package]
name = "semver-next"
version = "0.3.0"
edition = "2021"

[dependencies]
semver = "1.0.23"
clap = { version = "4.5.17", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
lazy_static = "1.5.0"

[lints.clippy]
pedantic = "deny"
